import pool from "../connection.js";

const currencies = ["NGN", "USD", "GBP"];

const seedDatabase = async () => {
  const client = await pool.connect();

  try {
    await client.query("DROP TABLE IF EXISTS currencies;");
    await client.query(
      "CREATE TABLE currencies (id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,currency_code varchar(3) UNIQUE);"
    );
    for (const currency of currencies) {
      try {
        await client.query(
          "INSERT INTO currencies (currency_code) VALUES ($1);",
          [currency]
        );
      } catch (error) {
        // Check if error is a unique violation (duplicate key)
        if (error.code === "23505") {
          continue;
        } else {
          console.error(error);
          throw error;
        }
      }
    }

    console.log("Database seeded successfully!");
  } catch (error) {
    console.error("Error seeding database:", error.message);
  } finally {
    client.release();
  }
};

export { currencies, seedDatabase };
