CREATE TABLE IF NOT EXISTS users (
  "id" UUID UNIQUE PRIMARY KEY NOT NULL DEFAULT (gen_random_uuid()),
  "first_name" varchar,
  "last_name" varchar,
  "email" varchar UNIQUE NOT NULL,
  "password" varchar NOT NULL,
  "address" varchar,
  "dob" date NOT NULL,
  "role" varchar DEFAULT 'user',
  "is_verified" boolean,
  "created_at" timestamp DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE IF NOT EXISTS tokens (
  id SERIAL PRIMARY KEY,
  user_id UUID REFERENCES users(id) ON DELETE CASCADE,
  token_type varchar(50) NOT NULL,
  token_hash varchar(255) NOT NULL,
  expiration_timestamp timestamp NOT NULL,
  created_at timestamp DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS currencies (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  currency_code varchar(3) UNIQUE,
  is_active boolean DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS expenses (
  "id" UUID UNIQUE PRIMARY KEY NOT NULL DEFAULT (gen_random_uuid()),
  "amount" numeric NOT NULL,
  "currency_code_id" integer,
  "created_by" UUID,
  "description" varchar,
  "is_settled" boolean,
  "created_at" timestamp DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE IF NOT EXISTS expense_participantS (
  "user_id" UUID,
  "expense_id" UUID,
  "is_settled" boolean,
  "payment_cut" numeric,
  "currency_code_id" integer,
  "comments" varchar,
  PRIMARY KEY ("user_id", "expense_id")
);

CREATE TABLE IF NOT EXISTS referrals (
  "referral_id" varchar PRIMARY KEY,
  "referring_user_id" UUID,
  "referred_user_id" UUID
);

CREATE TABLE IF NOT EXISTS user_sessions (
  "sid" varchar NOT NULL COLLATE "default",
  "sess" json NOT NULL,
  "expire" timestamp(6) NOT NULL
) WITH (OIDS = FALSE);

ALTER TABLE
  "user_sessions"
ADD
  CONSTRAINT "session_pkey" PRIMARY KEY ("sid") NOT DEFERRABLE INITIALLY IMMEDIATE;

CREATE INDEX "IDX_session_expire" ON "user_sessions" ("expire");

ALTER TABLE
  "expenses"
ADD
  FOREIGN KEY ("currency_code_id") REFERENCES "currencies" ("id");

ALTER TABLE
  "expenses"
ADD
  FOREIGN KEY ("created_by") REFERENCES "users" ("id");

ALTER TABLE
  "expense_participants"
ADD
  FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE
  "expense_participants"
ADD
  FOREIGN KEY ("expense_id") REFERENCES "expenses" ("id");

ALTER TABLE
  "expense_participants"
ADD
  FOREIGN KEY ("currency_code_id") REFERENCES "currencies" ("id");

ALTER TABLE
  "referrals"
ADD
  FOREIGN KEY ("referring_user_id") REFERENCES "users" ("id");

ALTER TABLE
  "referrals"
ADD
  FOREIGN KEY ("referred_user_id") REFERENCES "users" ("id");