CREATE TABLE "users" (
  "id" UUID UNIQUE PRIMARY KEY NOT NULL DEFAULT (gen_random_uuid()),
  "first_name" varchar,
  "last_name" varchar,
  "email" varchar UNIQUE NOT NULL,
  "password" varchar NOT NULL,
  "address" varchar,
  "dob" date NOT NULL,
  "role" varchar DEFAULT 'user',
  "is_verified" boolean,
  "password_reset_token" varchar,
  "created_at" timestamp DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE tokens (
  id SERIAL PRIMARY KEY,
  user_id UUID REFERENCES users(id) ON DELETE CASCADE,
  token_type VARCHAR(50) NOT NULL,
  token_hash VARCHAR(255) NOT NULL,
  expiration_timestamp timestamp NOT NULL,
  created_at timestamp DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "expenses" (
  "id" UUID UNIQUE PRIMARY KEY NOT NULL DEFAULT (gen_random_uuid()),
  "amount" decimal NOT NULL,
  "currency_code_id" varchar(3),
  "created_by" UUID,
  "description" varchar,
  "is_settled" boolean,
  "created_at" timestamp DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "expense_participants" (
  "user_id" UUID,
  "expense_id" UUID,
  "is_settled" boolean,
  "payment_cut" decimal,
  "currency_code_id" varchar(3),
  "comments" varchar,
  PRIMARY KEY ("user_id", "expense_id")
);

CREATE TABLE "referrals" (
  "referral_id" varchar[pk],
  "referring_user_id" UUID,
  "referred_user_id" UUID
);

CREATE TABLE "currencies" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "currency_code" varchar(3) UNIQUE
);

CREATE TABLE "user_sessions" (
  "sid" varchar NOT NULL COLLATE "default",
  "sess" json NOT NULL,
  "expire" timestamp(6) NOT NULL
)
WITH (OIDS=FALSE);

ALTER TABLE "user_sessions" ADD CONSTRAINT "session_pkey" PRIMARY KEY ("sid") NOT DEFERRABLE INITIALLY IMMEDIATE;

CREATE INDEX "IDX_session_expire" ON "user_sessions" ("expire");

ALTER TABLE "expenses" ADD FOREIGN KEY ("currency_code_id") REFERENCES "currencies" ("id");

ALTER TABLE "expenses" ADD FOREIGN KEY ("created_by") REFERENCES "users" ("id");

ALTER TABLE "expense_participants" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "expense_participants" ADD FOREIGN KEY ("expense_id") REFERENCES "expenses" ("id");

ALTER TABLE "expense_participants" ADD FOREIGN KEY ("currency_code_id") REFERENCES "currencies" ("id");

ALTER TABLE "referrals" ADD FOREIGN KEY ("referring_user_id") REFERENCES "users" ("id");

ALTER TABLE "referrals" ADD FOREIGN KEY ("referred_user_id") REFERENCES "users" ("id");
